version: "3.9"
services:
  backend:
    build: .
    image: runagen-backend:latest
    container_name: runagen-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/career-companion-472510-7dd10b4d4dcb.json
      - VERTEX_PROJECT_ID=${VERTEX_PROJECT_ID}
      - VERTEX_LOCATION=${VERTEX_LOCATION:-us-central1}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./career-companion-472510-7dd10b4d4dcb.json:/app/career-companion-472510-7dd10b4d4dcb.json:ro
    restart: unless-stopped
